apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: java-service-template
  title: Java Service Template
  description: Generates a simple Java service with a customizable package structure.
spec:
  owner: team@example.com
  type: service
  parameters:
    - title: Project Information
      properties:
        groupId:
          type: string
          description: The group ID for your project (e.g., com.example)
          default: "com.example"
        artifactId:
          type: string
          description: The artifact ID for your project
        version:
          type: string
          description: The version of your project (e.g., 1.0.0)
          default: "1.0.0"
        package:
          type: string
          description: The base Java package name (e.g., com.example.myapp)
          default: "{{ parameters.groupId }}.{{ parameters.artifactId }}"
  steps:
    - id: fetch-content
      name: Fetch Template
      action: fetch:template
      input:
        url: https://github.com/esebs/backstage-templates/tree/main/quarkus-template/skeleton
        values:
          groupId: '{{ parameters.groupId }}'
          artifactId: '{{ parameters.artifactId }}'
          version: '{{ parameters.version }}'
          package: '{{ parameters.package }}'
    - id: download-zip
      name: Download Project ZIP
      action: download:artifact
      input:
        artifactName: '{{ parameters.artifactId }}-service.zip'
        outputFileName: '{{ parameters.artifactId }}-service-project.zip'
